Repository kubernetes/kubectl, pull requests merged in 2018-05, with the labels that each got.

#456 fix glitch in hello world
  cmd/kustomize/demos/helloWorld.md
Labels: cncf-cla: yes, size/M

#457 add configGeneration to README in demos dir
  cmd/kustomize/demos/README.md
  cmd/kustomize/demos/configGeneration.md
Labels: cncf-cla: yes, size/S

#458 capture springboot demo data
  cmd/kustomize/demos/data/mySql/deployment.yaml
  cmd/kustomize/demos/data/mySql/secret.yaml
  cmd/kustomize/demos/data/mySql/service.yaml
  cmd/kustomize/demos/data/springboot/base/deployment.yaml
  cmd/kustomize/demos/data/springboot/base/service.yaml
  cmd/kustomize/demos/data/springboot/overlays/production/application.properties
  cmd/kustomize/demos/data/springboot/overlays/production/healthcheck_patch.yaml
  cmd/kustomize/demos/data/springboot/overlays/production/kustomization.yaml
  cmd/kustomize/demos/data/springboot/overlays/production/memorylimit_patch.yaml
  cmd/kustomize/demos/data/springboot/overlays/production/patch.yaml
  cmd/kustomize/demos/data/springboot/overlays/staging/application.properties
  cmd/kustomize/demos/data/springboot/overlays/staging/kustomization.yaml
  cmd/kustomize/demos/data/springboot/overlays/staging/staging.env
Labels: cncf-cla: yes, size/L

#459 Modify mysql and springboot demo to download their data from the code…
  cmd/kustomize/demos/mySql.md
  cmd/kustomize/demos/springboot.md
  cmd/kustomize/docs/kustomization.yaml
Labels: cncf-cla: yes, size/L

#462 Typo fix in the returned info.
  pkg/kustomize/commands/util_test.go
Labels: cncf-cla: yes, size/XS

#460 drop unused pngs
  cmd/kustomize/README.md
  cmd/kustomize/demos/README.md
  cmd/kustomize/demos/tree1.png
  cmd/kustomize/demos/tree2.png
  cmd/kustomize/docs/glossary.md
Labels: cncf-cla: yes, size/S

#463 Typo fix: defintion->definition
  cmd/kustomize/demos/configGeneration.md
Labels: cncf-cla: yes, size/XS

#464 Add ldap example to demo data
  cmd/kustomize/demos/data/ldap/base/deployment.yaml
  cmd/kustomize/demos/data/ldap/base/env.startup.txt
  cmd/kustomize/demos/data/ldap/base/kustomization.yaml
  cmd/kustomize/demos/data/ldap/base/service.yaml
  cmd/kustomize/demos/data/ldap/base/tests/test.sh
  cmd/kustomize/demos/data/ldap/overlays/production/deployment.yaml
  cmd/kustomize/demos/data/ldap/overlays/production/kustomization.yaml
  cmd/kustomize/demos/data/ldap/overlays/staging/config.env
  cmd/kustomize/demos/data/ldap/overlays/staging/deployment.yaml
  cmd/kustomize/demos/data/ldap/overlays/staging/kustomization.yaml
Labels: cncf-cla: yes, size/L

#467 Add ldap demo
  cmd/kustomize/demos/README.md
  cmd/kustomize/demos/ldap.md
Labels: cncf-cla: yes, size/L

#466 change test script to use ldap from the new location
  cmd/kustomize/test/main.sh
Labels: cncf-cla: yes, size/XS

#470 add apache license file for kustomize
  cmd/kustomize/CONTRIBUTING.md
  cmd/kustomize/LICENSE
  cmd/kustomize/OWNERS
  cmd/kustomize/demos/data/ldap/base/tests/test.sh
  cmd/kustomize/docs/kustomization.yaml
Labels: cncf-cla: yes, size/L

#471 Replace term 'instance' with 'variant'.
  cmd/kustomize/demos/README.md
  cmd/kustomize/demos/breakfast.md
  cmd/kustomize/demos/helloWorld.md
  cmd/kustomize/demos/ldap.md
  cmd/kustomize/docs/glossary.md
  cmd/kustomize/docs/workflows.md
Labels: approved, cncf-cla: yes, size/M

#472 reorderGloss
  cmd/kustomize/docs/glossary.md
Labels: approved, cncf-cla: yes, size/M

#474 updateFig2
  cmd/kustomize/docs/overlay.jpg
Labels: approved, cncf-cla: yes, size/XS

#477 Add myself to owners
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#482 Add owners section for subproject owners
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#484 add code of conduct
  cmd/kustomize/README.md
  cmd/kustomize/code-of-conduct.md
Labels: approved, cncf-cla: yes, size/S

#485 owner mods
  cmd/kustomize/OWNERS
  cmd/kustomize/OWNERS_ALIASES
Labels: approved, cncf-cla: yes, size/S

#469 Typo fix: cluser->cluster
  cmd/kustomize/docs/glossary.md
Labels: cncf-cla: yes, size/XS
