Repository kubernetes/kubectl, pull requests merged in 2018-02, with the labels that each got.

#272 fix demo
  cmd/kinflate/longerDemo/customization.md
  cmd/kinflate/longerDemo/editor.md
  cmd/kinflate/shortDemo.md
Labels: size/M

#273 add demo testing
  .travis.yml
  bin/pre-commit.sh
  cmd/kinflate/longerDemo/base.md
  cmd/kinflate/longerDemo/customization.md
  cmd/kinflate/longerDemo/editor.md
  cmd/kinflate/longerDemo/identity.md
  cmd/kinflate/longerDemo/instances/compare.md
  cmd/kinflate/longerDemo/manifest.md
Labels: cncf-cla: yes, size/M

#275 fix a typo init.go
  pkg/kinflate/commands/init.go
Labels: cncf-cla: yes, size/XS

#274 Kinflate use manifest tree builder
  cmd/kinflate/longerDemo/instances/production.md
  cmd/kinflate/longerDemo/instances/staging.md
  pkg/kinflate/commands/inflate.go
  pkg/kinflate/examples/simple/instances/exampleinstance/Kube-manifest.yaml
  pkg/kinflate/mergemap/merge.go
  pkg/kinflate/transformers/default.go
  pkg/kinflate/transformers/overlay.go
  pkg/kinflate/transformers/overlay_test.go
  pkg/kinflate/tree/builder.go
  pkg/kinflate/tree/builder_test.go
  pkg/kinflate/tree/default.go
  pkg/kinflate/tree/node.go
  pkg/kinflate/types/util.go
  pkg/kinflate/util.go
  pkg/kinflate/util_test.go
Labels: cncf-cla: yes, size/XXL

#279 error out when a patch has not matching object
  pkg/kinflate/transformers/overlay.go
Labels: cncf-cla: yes, size/M

#281 Noop transformer
  pkg/kinflate/transformers/labelsandannotations.go
  pkg/kinflate/transformers/nooptransformer.go
  pkg/kinflate/transformers/overlay.go
  pkg/kinflate/transformers/prefixname.go
  pkg/kinflate/tree/default.go
Labels: cncf-cla: yes, size/M

#283 Add links to existing demo and tutorial pages.
  cmd/kinflate/README.md
  cmd/kinflate/longerDemo/README.md
  cmd/kinflate/longerDemo/base.md
  cmd/kinflate/longerDemo/customization.md
  cmd/kinflate/longerDemo/identity.md
  cmd/kinflate/longerDemo/instances/README.md
  cmd/kinflate/longerDemo/instances/compare.md
  cmd/kinflate/longerDemo/instances/production.md
  cmd/kinflate/longerDemo/instances/staging.md
  cmd/kinflate/longerDemo/lifecycle.md
  cmd/kinflate/longerDemo/manifest.md
  cmd/kinflate/longerDemo/resources.md
  cmd/kinflate/shortDemo.md
Labels: cncf-cla: yes, size/M

#280 More specific error messages for missing/bad manifest file
  pkg/kinflate/constants/constants.go
  pkg/kinflate/util/manifestloader.go
  pkg/kinflate/util/manifestloader_test.go
Labels: cncf-cla: yes, size/M

#284 Make test failures easier to see and understand.
  bin/pre-commit.sh
Labels: cncf-cla: yes, size/M

#289 Checkpoint toward better kinflate error messages.
  pkg/kinflate/commands/inflate.go
  pkg/kinflate/tree/builder.go
  pkg/kinflate/tree/builder_test.go
  pkg/kinflate/util/manifestloader.go
  pkg/kinflate/util/manifestloader_test.go
Labels: cncf-cla: yes, size/L

#282 WIP: fix filesystem tech debt
  pkg/kinflate/commands/inflate.go
  pkg/kinflate/tree/builder.go
  pkg/kinflate/tree/builder_test.go
  pkg/kinflate/util/manifestloader.go
  pkg/kinflate/util/manifestloader_test.go
Labels: cncf-cla: yes, do-not-merge/work-in-progress, size/L

#294 New structure: ManifestError
  pkg/kinflate/util/manifesterror.go
  pkg/kinflate/util/manifesterror_test.go
Labels: area/kinflate, cncf-cla: yes, size/M

#296 kinflate: removed non-existing resources from manifest file
  pkg/kinflate/commands/addresource_test.go
  pkg/kinflate/commands/commands.go
  pkg/kinflate/commands/init.go
Labels: cncf-cla: yes, size/M

#299 better integration test
  pkg/kinflate/commands/inflate_test.go
  pkg/kinflate/commands/testdata/testcase-base-only/expected.yaml
  pkg/kinflate/commands/testdata/testcase-base-only/in/Kube-manifest.yaml
  pkg/kinflate/commands/testdata/testcase-base-only/in/deployment.yaml
  pkg/kinflate/commands/testdata/testcase-base-only/in/service.yaml
  pkg/kinflate/commands/testdata/testcase-base-only/test.yaml
  pkg/kinflate/commands/testdata/testcase-simple/expected.yaml
  pkg/kinflate/commands/testdata/testcase-simple/test.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/expected.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/overlay/Kube-manifest.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/overlay/deployment.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/package/Kube-manifest.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/package/deployment.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/package/service.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/test.yaml
Labels: cncf-cla: yes, size/L

#285 kinflate: Generate secrets with commands
  pkg/apis/manifest/v1alpha1/types.go
  pkg/kinflate/commands/commands.go
  pkg/kinflate/commands/secret.go
  pkg/kinflate/commands/secret_test.go
  pkg/kinflate/configmapandsecret/configmap_secret.go
  pkg/kinflate/configmapandsecret/configmap_secret_test.go
  pkg/kinflate/examples/simple/instances/exampleinstance/Kube-manifest.yaml
  pkg/kinflate/tree/builder.go
  pkg/kinflate/util/adjust_path.go
Labels: cncf-cla: yes, size/XL

#297 kinflate: improved README and added getting-started
  cmd/kinflate/README.md
  cmd/kinflate/getting_started.md
Labels: cncf-cla: yes, size/L

#303 Create different internal error types
  pkg/kinflate/internal/error/configmaperror.go
  pkg/kinflate/internal/error/configmaperror_test.go
  pkg/kinflate/internal/error/manifesterror.go
  pkg/kinflate/internal/error/manifesterror_test.go
  pkg/kinflate/internal/error/patcherror.go
  pkg/kinflate/internal/error/patcherror_test.go
  pkg/kinflate/internal/error/resourceerror.go
  pkg/kinflate/internal/error/resourceerror_test.go
  pkg/kinflate/internal/error/secreterror.go
  pkg/kinflate/internal/error/secreterror_test.go
Labels: cncf-cla: yes, size/L

#307 initial implementation for file loader
  pkg/loader/factory.go
  pkg/loader/fake/fakefileloader.go
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
  pkg/loader/loader.go
Labels: cncf-cla: yes, size/L

#292 add kinflate diff command
  Gopkg.lock
  Gopkg.toml
  pkg/kinflate/commands/commands.go
  pkg/kinflate/commands/diff.go
  pkg/kinflate/commands/inflate.go
  pkg/kinflate/commands/inflate_test.go
  pkg/kinflate/commands/testdata/testcase-base-only/test.yaml
  pkg/kinflate/commands/testdata/testcase-noop/Kube-manifest.yaml
  pkg/kinflate/commands/testdata/testcase-noop/configmap/app-init.ini
  pkg/kinflate/commands/testdata/testcase-noop/configmap/app.env
  pkg/kinflate/commands/testdata/testcase-noop/expected.yaml
  pkg/kinflate/commands/testdata/testcase-noop/mysql/Kube-manifest.yaml
  pkg/kinflate/commands/testdata/testcase-noop/mysql/deployment.yaml
  pkg/kinflate/commands/testdata/testcase-noop/mysql/service.yaml
  pkg/kinflate/commands/testdata/testcase-noop/patch.yaml
  pkg/kinflate/commands/testdata/testcase-noop/test.yaml
  pkg/kinflate/commands/testdata/testcase-noop/wordpress/Kube-manifest.yaml
  pkg/kinflate/commands/testdata/testcase-noop/wordpress/deployment.yaml
  pkg/kinflate/commands/testdata/testcase-noop/wordpress/service.yaml
  pkg/kinflate/commands/testdata/testcase-simple/test.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/test.yaml
  pkg/kinflate/tree/node.go
  pkg/kinflate/types/util.go
  pkg/kinflate/util/diff.go
  pkg/kinflate/util/util.go
  vendor/k8s.io/utils/.travis.yml
  vendor/k8s.io/utils/HOWTOMOVE.md
  vendor/k8s.io/utils/LICENSE
  vendor/k8s.io/utils/README.md
  vendor/k8s.io/utils/clock/clock.go
  vendor/k8s.io/utils/clock/testing/fake_clock.go
  vendor/k8s.io/utils/clock/testing/fake_clock_test.go
  vendor/k8s.io/utils/code-of-conduct.md
  vendor/k8s.io/utils/exec/doc.go
  vendor/k8s.io/utils/exec/exec.go
  vendor/k8s.io/utils/exec/exec_test.go
  vendor/k8s.io/utils/exec/new_test.go
  vendor/k8s.io/utils/exec/testing/fake_exec.go
  vendor/k8s.io/utils/temp/dir.go
  vendor/k8s.io/utils/temp/dir_test.go
  vendor/k8s.io/utils/temp/doc.go
  vendor/k8s.io/utils/temp/temptest/dir.go
  vendor/k8s.io/utils/temp/temptest/dir_test.go
  vendor/k8s.io/utils/temp/temptest/doc.go
  vendor/k8s.io/utils/temp/temptest/example_test.go
  vendor/k8s.io/utils/temp/temptest/file.go
  vendor/k8s.io/utils/temp/temptest/file_test.go
Labels: cncf-cla: yes, size/XXL

#308 Move ManifestLoader under tree package
  pkg/kinflate/commands/addresource.go
  pkg/kinflate/commands/configmap.go
  pkg/kinflate/commands/inflate.go
  pkg/kinflate/tree/adjust_path.go
  pkg/kinflate/tree/builder.go
  pkg/kinflate/tree/builder_test.go
  pkg/kinflate/tree/manifestloader.go
  pkg/kinflate/tree/manifestloader_test.go
Labels: cncf-cla: yes, size/M

#309 removed '-u' option from install command
  cmd/kinflate/README.md
Labels: cncf-cla: yes, size/XS

#311 Use ManifestLoader to read and write the kubemanifest file
  pkg/kinflate/commands/set_name_prefix.go
Labels: cncf-cla: yes, size/S

#312 First pass at Application abstraction with unimplemented methods
  pkg/kinflate/app/application.go
  pkg/kinflate/resource/resource.go
Labels: cncf-cla: yes, size/M

#310 update yaml import pkg
  pkg/kinflate/commands/inflate_test.go
Labels: cncf-cla: yes, size/XS

#315 Refactor Loader interface
  pkg/loader/fake/fakefileloader.go
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
  pkg/loader/loader.go
  pkg/loader/loader_test.go
Labels: cncf-cla: yes, size/L

#313 added configmap resource implementation
  pkg/kinflate/resource/configmap.go
  pkg/kinflate/resource/resource.go
Labels: cncf-cla: yes, size/L

#314 Add appresource implementation
  pkg/kinflate/resource/appresource.go
  pkg/kinflate/resource/appresource_test.go
  pkg/kinflate/tree/builder.go
  pkg/kinflate/util/util.go
  pkg/kinflate/util/util_test.go
Labels: cncf-cla: yes, size/L

#318 kinflate/transformers: Keep private things private
  pkg/kinflate/transformers/labelsandannotations.go
  pkg/kinflate/transformers/multitransformer.go
  pkg/kinflate/transformers/namereference.go
  pkg/kinflate/transformers/nooptransformer.go
  pkg/kinflate/transformers/overlay.go
  pkg/kinflate/transformers/prefixname.go
Labels: cncf-cla: yes, size/L

#319 Add secret resource
  pkg/kinflate/resource/secret.go
  pkg/kinflate/resource/secret_test.go
Labels: cncf-cla: yes, size/L

#316 configmap resource implementation using loader
  pkg/kinflate/resource/appresource_test.go
  pkg/kinflate/resource/configmap.go
  pkg/kinflate/resource/configmap_test.go
  pkg/kinflate/resource/kv.go
  pkg/kinflate/resource/kv_test.go
  pkg/loader/fake_loader.go
Labels: cncf-cla: yes, size/L

#321 change function name from ResourceFromPath to NewFromPath
  pkg/kinflate/resource/appresource.go
  pkg/kinflate/resource/appresource_test.go
Labels: cncf-cla: yes, size/XS

#317 Refactor Loader interface
  pkg/loader/fake_loader.go
  pkg/loader/fileloader.go
  pkg/loader/fileloader_test.go
  pkg/loader/loader.go
  pkg/loader/loader_test.go
Labels: cncf-cla: yes, size/L

#323 Move fake loader into its own package; Update loader test
  pkg/kinflate/resource/appresource_test.go
  pkg/kinflate/resource/configmap_test.go
  pkg/loader/loader_test.go
  pkg/loader/loadertest/fake_loader.go
Labels: cncf-cla: yes, size/L

#327 Update FakeLoader for simpler interface; FakeLoader uses real Loader
  pkg/kinflate/resource/appresource_test.go
  pkg/kinflate/resource/configmap_test.go
  pkg/loader/loadertest/fake_loader.go
Labels: cncf-cla: yes, size/M

#329 Add nameHashTransformer
  pkg/kinflate/transformers/labelsandannotations_test.go
  pkg/kinflate/transformers/namehash.go
  pkg/kinflate/transformers/namehash_test.go
Labels: cncf-cla: yes, size/L

#328 Simplified Loader.New() to always take a directory
  pkg/kinflate/resource/configmap_test.go
  pkg/loader/fileloader.go
  pkg/loader/loader.go
  pkg/loader/loader_test.go
  pkg/loader/loadertest/fake_loader.go
Labels: cncf-cla: yes, size/M
