Repository kubernetes/kubectl, pull requests merged in 2018-04, with the labels that each got.

#388 Add glossary
  cmd/kinflate/README.md
  cmd/kinflate/glossary.md
  cmd/kinflate/workflows.md
Labels: cncf-cla: yes, size/L

#390 kinflate: added version command
  cmd/kinflate/version/version.go
  pkg/kinflate/commands/commands.go
Labels: cncf-cla: yes, lgtm, size/M

#383 Return rest config and regular config from pluginutil Init method
  pkg/pluginutils/plugin_client.go
  pkg/pluginutils/plugin_client_test.go
Labels: cncf-cla: yes, size/M

#389 add workflow figs
  cmd/kinflate/README.md
  cmd/kinflate/docs/glossary.md
  cmd/kinflate/docs/workflowBespoke.jpg
  cmd/kinflate/docs/workflowOts.jpg
  cmd/kinflate/docs/workflows.md
  cmd/kinflate/workflows.md
Labels: cncf-cla: yes, size/L

#373 Add different behavior for configmaps in overlay
  pkg/apis/manifest/v1alpha1/types.go
  pkg/kinflate/app/application.go
  pkg/kinflate/app/application_test.go
  pkg/kinflate/commands/testdata/testcase-simple/expected.diff
  pkg/kinflate/commands/testdata/testcase-simple/expected.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/expected.diff
  pkg/kinflate/commands/testdata/testcase-single-overlay/expected.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/overlay/Kube-manifest.yaml
  pkg/kinflate/constants/constants.go
  pkg/kinflate/resource/configmap.go
  pkg/kinflate/resource/resource.go
  pkg/kinflate/resource/util.go
Labels: cncf-cla: yes, size/L

#393 Add different behavior for secretGenerator in overlay
  pkg/apis/manifest/v1alpha1/types.go
  pkg/kinflate/commands/testdata/testcase-single-overlay/expected.diff
  pkg/kinflate/commands/testdata/testcase-single-overlay/expected.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/overlay/Kube-manifest.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/package/Kube-manifest.yaml
  pkg/kinflate/resource/secret.go
Labels: cncf-cla: yes, size/M

#395 kinflate: add build automation
  cmd/kinflate/build/README.md
  cmd/kinflate/build/build.sh
  cmd/kinflate/build/cloudbuild.yaml
  cmd/kinflate/build/cloudbuild_local.yaml
Labels: cncf-cla: yes, size/L

#403 kinflate: remove prune field from the manifest
  pkg/apis/manifest/v1alpha1/types.go
  pkg/kinflate/commands/init.go
  pkg/kinflate/examples/simple/instances/exampleinstance/Kube-manifest.yaml
Labels: cncf-cla: yes, size/S

#402 some wording tweaks
  cmd/kinflate/docs/workflowBespoke.jpg
  cmd/kinflate/docs/workflowOts.jpg
  cmd/kinflate/docs/workflows.md
Labels: cncf-cla: yes, size/S

#404 Remove the -f option of inflate
  cmd/kinflate/demo/helloWorldDetailed/customize.md
  cmd/kinflate/demo/helloWorldDetailed/manifest.md
  cmd/kinflate/demo/helloWorldDetailed/overlays/deploy.md
  cmd/kinflate/demo/helloWorldOnePager.md
  cmd/kinflate/demo/mySql.md
  pkg/kinflate/commands/inflate.go
  pkg/kinflate/commands/inflate_test.go
Labels: cncf-cla: yes, size/M

#409 update vendor apimachinery
  Gopkg.lock
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/duration.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/time.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured_list.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured_test.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/apimachinery/pkg/runtime/interfaces.go
  vendor/k8s.io/apimachinery/pkg/runtime/schema/group_version_test.go
  vendor/k8s.io/apimachinery/pkg/runtime/testing/types.go
  vendor/k8s.io/apimachinery/pkg/types/namespacedname.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper_test.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go
  vendor/k8s.io/apimachinery/pkg/watch/filter.go
  vendor/k8s.io/apimachinery/pkg/watch/mux.go
Labels: cncf-cla: yes, size/L

#412 add tree output to demo
  cmd/kinflate/demo/helloWorld.md
  cmd/kinflate/demo/tree1.png
  cmd/kinflate/demo/tree2.png
Labels: cncf-cla: yes, size/M

#406 Add logging for replacing and merging configmap and secrets
  pkg/kinflate/resource/util.go
Labels: cncf-cla: yes, lgtm, size/XS

#414 Command organization - build and edit
  cmd/kinflate/demos/helloWorld.md
  cmd/kinflate/demos/mySql.md
  cmd/kinflate/version/version.go
  pkg/kinflate/commands/build.go
  pkg/kinflate/commands/build_test.go
  pkg/kinflate/commands/commands.go
  pkg/kinflate/commands/configmap.go
  pkg/kinflate/commands/diff_test.go
  pkg/kinflate/commands/init.go
Labels: cncf-cla: yes, size/L

#405 Add springboot example demo
  cmd/kinflate/demos/README.md
  cmd/kinflate/demos/springboot.md
Labels: cncf-cla: yes, size/L

#375 Conflict detection in kinflate
  pkg/kinflate/commands/build_test.go
  pkg/kinflate/commands/diff_test.go
  pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/in/overlay/Kube-manifest.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/in/overlay/deployment-patch1.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/in/overlay/deployment-patch2.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/in/package/Kube-manifest.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/in/package/deployment.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/in/package/service.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/test.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/expected.diff
  pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/expected.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/in/overlay/Kube-manifest.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/in/overlay/deployment-patch1.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/in/overlay/deployment-patch2.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/in/package/Kube-manifest.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/in/package/deployment.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/in/package/service.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/test.yaml
  pkg/kinflate/transformers/overlay.go
  pkg/kinflate/transformers/overlay_test.go
  pkg/kinflate/transformers/overlayconflictdetector.go
Labels: cncf-cla: yes, size/XXL

#416 structure for manifest documentation
  cmd/kinflate/Makefile
  cmd/kinflate/docs/Kube-manifest.yaml
  cmd/kinflate/docs/glossary.md
Labels: cncf-cla: yes, size/M

#420 change Kube-manifest.yaml to kustomize.yaml
  cmd/kinflate/demos/helloWorld.md
  cmd/kinflate/demos/mySql.md
  cmd/kinflate/demos/springboot.md
  cmd/kinflate/docs/glossary.md
  pkg/apis/manifest/v1alpha1/types.go
  pkg/kinflate/app/application.go
  pkg/kinflate/app/application_test.go
  pkg/kinflate/commands/addresource.go
  pkg/kinflate/commands/addresource_test.go
  pkg/kinflate/commands/build.go
  pkg/kinflate/commands/configmap.go
  pkg/kinflate/commands/diff.go
  pkg/kinflate/commands/init.go
  pkg/kinflate/commands/init_test.go
  pkg/kinflate/commands/set_name_prefix.go
  pkg/kinflate/commands/set_name_prefix_test.go
  pkg/kinflate/commands/testdata/testcase-base-only/in/kustomize.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/in/overlay/kustomize.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/in/package/kustomize.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/in/overlay/kustomize.yaml
  pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/in/package/kustomize.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/overlay/kustomize.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/package/kustomize.yaml
  pkg/kinflate/commands/util.go
  pkg/kinflate/commands/util_test.go
  pkg/kinflate/constants/constants.go
  pkg/kinflate/examples/simple/instances/exampleinstance/kustomize.yaml
  pkg/kinflate/examples/simple/package/kustomize.yaml
  pkg/kinflate/internal/error/configmaperror_test.go
  pkg/kinflate/internal/error/manifesterror_test.go
  pkg/kinflate/internal/error/patcherror_test.go
  pkg/kinflate/internal/error/resourceerror_test.go
Labels: cncf-cla: yes, size/L

#419 swtich to depend on the scheme in client-go
  pkg/kinflate/transformers/overlay.go
  pkg/scheme/scheme.go
Labels: cncf-cla: yes, size/M

#423 Test config map names
  cmd/kinflate/demos/helloWorld.md
Labels: cncf-cla: yes, size/L

#368 updated namereference config for missing references.
  pkg/kustomize/transformers/namereferenceconfig.go
Labels: cncf-cla: yes, size/L

#433 Remove init and manifest from demos
  cmd/kustomize/demos/mySql.md
  cmd/kustomize/demos/springboot.md
Labels: cncf-cla: yes, size/L

#437 Drop k8s metadata fields from kustomize.yaml struct
  cmd/kustomize/demos/helloWorld.md
  pkg/apis/manifest/v1alpha1/doc.go
  pkg/kustomize/app/application.go
  pkg/kustomize/app/application_test.go
  pkg/kustomize/commands/configmap.go
  pkg/kustomize/commands/configmap_test.go
  pkg/kustomize/commands/testdata/testcase-base-only/in/kustomize.yaml
  pkg/kustomize/commands/testdata/testcase-multiple-patches-conflict/in/overlay/kustomize.yaml
  pkg/kustomize/commands/testdata/testcase-multiple-patches-conflict/in/package/kustomize.yaml
  pkg/kustomize/commands/testdata/testcase-multiple-patches-noconflict/in/overlay/kustomize.yaml
  pkg/kustomize/commands/testdata/testcase-multiple-patches-noconflict/in/package/kustomize.yaml
  pkg/kustomize/commands/testdata/testcase-single-overlay/in/overlay/kustomize.yaml
  pkg/kustomize/commands/testdata/testcase-single-overlay/in/package/kustomize.yaml
  pkg/kustomize/commands/util.go
  pkg/kustomize/commands/util_test.go
  pkg/kustomize/configmapandsecret/configmap_secret.go
  pkg/kustomize/configmapandsecret/configmap_secret_test.go
  pkg/kustomize/examples/simple/instances/exampleinstance/kustomize.yaml
  pkg/kustomize/examples/simple/package/kustomize.yaml
  pkg/kustomize/resource/configmap.go
  pkg/kustomize/resource/configmap_test.go
  pkg/kustomize/resource/secret.go
  pkg/kustomize/resource/secret_test.go
  pkg/kustomize/types/manifest.go
Labels: cncf-cla: yes, size/L

#438 manifest becomes kustomization
  cmd/kustomize/Makefile
  cmd/kustomize/README.md
  cmd/kustomize/demos/helloWorld.md
  cmd/kustomize/docs/glossary.md
  cmd/kustomize/docs/kustomize.yaml
  cmd/kustomize/docs/workflows.md
  pkg/framework/openapi/testing/openapi.go
  pkg/kustomize/app/application.go
  pkg/kustomize/app/application_test.go
  pkg/kustomize/commands/addresource.go
  pkg/kustomize/commands/addresource_test.go
  pkg/kustomize/commands/build.go
  pkg/kustomize/commands/build_test.go
  pkg/kustomize/commands/commands.go
  pkg/kustomize/commands/configmap.go
  pkg/kustomize/commands/configmap_test.go
  pkg/kustomize/commands/diff.go
  pkg/kustomize/commands/diff_test.go
  pkg/kustomize/commands/init.go
  pkg/kustomize/commands/init_test.go
  pkg/kustomize/commands/set_name_prefix.go
  pkg/kustomize/commands/set_name_prefix_test.go
  pkg/kustomize/commands/util.go
  pkg/kustomize/commands/util_test.go
  pkg/kustomize/constants/constants.go
  pkg/kustomize/internal/error/configmaperror.go
  pkg/kustomize/internal/error/configmaperror_test.go
  pkg/kustomize/internal/error/kustomizationerror.go
  pkg/kustomize/internal/error/kustomizationerror_test.go
  pkg/kustomize/internal/error/manifesterror_test.go
  pkg/kustomize/internal/error/patcherror.go
  pkg/kustomize/internal/error/patcherror_test.go
  pkg/kustomize/internal/error/resourceerror.go
  pkg/kustomize/internal/error/resourceerror_test.go
  pkg/kustomize/internal/error/secreterror.go
  pkg/kustomize/internal/error/secreterror_test.go
  pkg/kustomize/resource/appresource.go
  pkg/kustomize/resource/configmap.go
  pkg/kustomize/types/kustomization.go
Labels: cncf-cla: yes, size/XL

#439 Drop the init command
  cmd/kustomize/Makefile
  cmd/kustomize/docs/kustomize.yaml
  pkg/kustomize/commands/addresource_test.go
  pkg/kustomize/commands/commands.go
  pkg/kustomize/commands/init.go
  pkg/kustomize/commands/init_test.go
  pkg/kustomize/commands/set_name_prefix_test.go
Labels: cncf-cla: yes, size/L

#441 Some kustomization field renaming.
  cmd/kustomize/demos/helloWorld.md
  cmd/kustomize/demos/mySql.md
  cmd/kustomize/demos/springboot.md
  cmd/kustomize/docs/kustomize.yaml
  pkg/kustomize/app/application.go
  pkg/kustomize/app/application_test.go
  pkg/kustomize/commands/init.go
  pkg/kustomize/commands/testdata/testcase-base-only/in/kustomize.yaml
  pkg/kustomize/commands/testdata/testcase-multiple-patches-conflict/in/overlay/kustomize.yaml
  pkg/kustomize/commands/testdata/testcase-multiple-patches-conflict/in/package/kustomize.yaml
  pkg/kustomize/commands/testdata/testcase-multiple-patches-noconflict/in/overlay/kustomize.yaml
  pkg/kustomize/commands/testdata/testcase-multiple-patches-noconflict/in/package/kustomize.yaml
  pkg/kustomize/commands/testdata/testcase-single-overlay/in/overlay/kustomize.yaml
  pkg/kustomize/commands/testdata/testcase-single-overlay/in/package/kustomize.yaml
  pkg/kustomize/examples/simple/instances/exampleinstance/kustomize.yaml
  pkg/kustomize/examples/simple/package/kustomize.yaml
  pkg/kustomize/types/kustomization.go
Labels: cncf-cla: yes, size/L

#442 Update figs
  cmd/kustomize/docs/base.jpg
  cmd/kustomize/docs/glossary.md
  cmd/kustomize/docs/overlay.jpg
Labels: cncf-cla: yes, size/XS

#443 updated figs
  cmd/kustomize/docs/base.jpg
  cmd/kustomize/docs/overlay.jpg
Labels: cncf-cla: yes, size/XS

#440 Example kustomize.yaml
  cmd/kustomize/docs/kustomize.yaml
Labels: cncf-cla: yes, size/L

#445 kustomize.yaml becomes kustomization.yaml
  cmd/kustomize/demos/helloWorld.md
  cmd/kustomize/demos/mySql.md
  cmd/kustomize/demos/springboot.md
  cmd/kustomize/docs/glossary.md
  cmd/kustomize/docs/kustomization.yaml
  pkg/kustomize/app/application.go
  pkg/kustomize/app/application_test.go
  pkg/kustomize/commands/build.go
  pkg/kustomize/commands/build_test.go
  pkg/kustomize/commands/diff.go
  pkg/kustomize/commands/init.go
  pkg/kustomize/commands/testdata/testcase-base-only/in/kustomization.yaml
  pkg/kustomize/commands/testdata/testcase-multiple-patches-conflict/in/overlay/kustomization.yaml
  pkg/kustomize/commands/testdata/testcase-multiple-patches-conflict/in/package/kustomization.yaml
  pkg/kustomize/commands/testdata/testcase-multiple-patches-noconflict/in/overlay/kustomization.yaml
  pkg/kustomize/commands/testdata/testcase-multiple-patches-noconflict/in/package/kustomization.yaml
  pkg/kustomize/commands/testdata/testcase-single-overlay/in/overlay/kustomization.yaml
  pkg/kustomize/commands/testdata/testcase-single-overlay/in/package/kustomization.yaml
  pkg/kustomize/commands/util_test.go
  pkg/kustomize/constants/constants.go
  pkg/kustomize/examples/simple/instances/exampleinstance/kustomization.yaml
  pkg/kustomize/examples/simple/package/kustomization.yaml
  pkg/kustomize/internal/error/configmaperror_test.go
  pkg/kustomize/internal/error/kustomizationerror_test.go
  pkg/kustomize/internal/error/patcherror_test.go
  pkg/kustomize/internal/error/resourceerror_test.go
  pkg/kustomize/types/kustomization.go
Labels: cncf-cla: yes, size/L

#446 new figs
  cmd/kustomize/docs/base.jpg
  cmd/kustomize/docs/overlay.jpg
Labels: cncf-cla: yes, size/XS

#448 add a tested breakfast configuration demo
  cmd/kustomize/README.md
  cmd/kustomize/demos/README.md
  cmd/kustomize/demos/breakfast.md
  cmd/kustomize/docs/glossary.md
Labels: cncf-cla: yes, size/L

#452 Typo fix: resourse->resource
  cmd/kustomize/docs/glossary.md
Labels: cncf-cla: yes, size/XS

#447 Typo fix in glossary.md
  cmd/kustomize/demos/README.md
  cmd/kustomize/docs/glossary.md
Labels: cncf-cla: yes, size/XS

#453 configmapgenerator example
  cmd/kustomize/demos/configmaps.md
Labels: cncf-cla: yes, size/L

#455 pull helloWorld demo data into code repo
  cmd/kustomize/demos/data/helloWorld/configMap.yaml
  cmd/kustomize/demos/data/helloWorld/deployment.yaml
  cmd/kustomize/demos/data/helloWorld/kustomization.yaml
  cmd/kustomize/demos/data/helloWorld/service.yaml
  cmd/kustomize/demos/helloWorld.md
  cmd/kustomize/docs/glossary.md
Labels: cncf-cla: yes, size/L
