Repository kubernetes/kubectl, pull requests merged in 2018-03, with the labels that each got.

#331 update resource package
  pkg/kinflate/resource/appresource.go
  pkg/kinflate/resource/appresource_test.go
  pkg/kinflate/resource/configmap.go
  pkg/kinflate/resource/configmap_test.go
  pkg/kinflate/resource/secret.go
  pkg/kinflate/resource/secret_test.go
Labels: cncf-cla: yes, size/L

#322 implement Resources func for applicationImpl
  pkg/kinflate/app/application.go
  pkg/kinflate/app/application_test.go
  pkg/kinflate/types/types.go
Labels: cncf-cla: yes, lgtm, size/L

#333 Change inflate to use Application interface
  pkg/kinflate/commands/inflate.go
Labels: cncf-cla: yes, size/M

#340 fall back to JSON merge patch for types w/o schema (CRD)
  Gopkg.lock
  pkg/kinflate/transformers/overlay.go
  pkg/kinflate/transformers/overlay_test.go
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/cmd/json-patch/file_flag.go
  vendor/github.com/evanphx/json-patch/cmd/json-patch/main.go
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/merge_test.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/evanphx/json-patch/patch_test.go
Labels: cncf-cla: yes, size/XXL

#341 Add util functions to read/write manifest file and update sub commands
  pkg/kinflate/commands/addresource.go
  pkg/kinflate/commands/configmap.go
  pkg/kinflate/commands/set_name_prefix.go
  pkg/kinflate/commands/util.go
  pkg/kinflate/commands/util_test.go
Labels: cncf-cla: yes, size/L

#343 Remove package tree
  pkg/kinflate/tree/adjust_path.go
  pkg/kinflate/tree/builder.go
  pkg/kinflate/tree/builder_test.go
  pkg/kinflate/tree/default.go
  pkg/kinflate/tree/manifestloader.go
  pkg/kinflate/tree/manifestloader_test.go
  pkg/kinflate/tree/node.go
  pkg/kinflate/tree/testdata/hierarchy/Kube-manifest.yaml
  pkg/kinflate/tree/testdata/hierarchy/parent1/Kube-manifest.yaml
  pkg/kinflate/tree/testdata/hierarchy/parent1/child1/Kube-manifest.yaml
  pkg/kinflate/tree/testdata/hierarchy/parent2/Kube-manifest.yaml
  pkg/kinflate/tree/testdata/hierarchy/parent2/child2/Kube-manifest.yaml
  pkg/kinflate/tree/testdata/valid/Kube-manifest.yaml
  pkg/kinflate/tree/testdata/valid/cm/configmap.yaml
  pkg/kinflate/tree/testdata/valid/patch.yaml
  pkg/kinflate/tree/testdata/valid/pod.yaml
Labels: cncf-cla: yes, size/XXL

#344 appending name hash only applies to current layer
  pkg/kinflate/app/application.go
  pkg/kinflate/commands/testdata/testcase-single-overlay/expected.diff
  pkg/kinflate/commands/testdata/testcase-single-overlay/expected.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/overlay/Kube-manifest.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/overlay/deployment.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/package/Kube-manifest.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/package/deployment.yaml
Labels: cncf-cla: yes, size/L

#349 Rename KObject to ResourceCollection
  pkg/kinflate/app/application.go
  pkg/kinflate/commands/diff.go
  pkg/kinflate/commands/inflate.go
  pkg/kinflate/configmapandsecret/configmap_secret.go
  pkg/kinflate/transformers/labelsandannotations.go
  pkg/kinflate/transformers/labelsandannotations_test.go
  pkg/kinflate/transformers/multitransformer.go
  pkg/kinflate/transformers/namehash.go
  pkg/kinflate/transformers/namehash_test.go
  pkg/kinflate/transformers/namereference.go
  pkg/kinflate/transformers/namereference_test.go
  pkg/kinflate/transformers/nooptransformer.go
  pkg/kinflate/transformers/overlay.go
  pkg/kinflate/transformers/overlay_test.go
  pkg/kinflate/transformers/prefixname.go
  pkg/kinflate/transformers/transformer.go
  pkg/kinflate/transformers/util_test.go
  pkg/kinflate/types/types.go
  pkg/kinflate/util/util.go
  pkg/kinflate/util/util_test.go
Labels: cncf-cla: yes, size/L

#350 cleanup Resouce slice related code
  pkg/kinflate/app/application.go
  pkg/kinflate/app/application_test.go
  pkg/kinflate/configmapandsecret/configmap_secret.go
  pkg/kinflate/resource/appresource.go
  pkg/kinflate/resource/appresource_test.go
  pkg/kinflate/resource/configmap.go
  pkg/kinflate/resource/configmap_test.go
  pkg/kinflate/resource/resource.go
  pkg/kinflate/resource/secret.go
  pkg/kinflate/resource/secret_test.go
  pkg/kinflate/resource/util.go
  pkg/kinflate/resource/util_test.go
  pkg/kinflate/transformers/labelsandannotations.go
  pkg/kinflate/transformers/labelsandannotations_test.go
  pkg/kinflate/transformers/multitransformer.go
  pkg/kinflate/transformers/namehash.go
  pkg/kinflate/transformers/namehash_test.go
  pkg/kinflate/transformers/namereference.go
  pkg/kinflate/transformers/namereference_test.go
  pkg/kinflate/transformers/nooptransformer.go
  pkg/kinflate/transformers/overlay.go
  pkg/kinflate/transformers/overlay_test.go
  pkg/kinflate/transformers/prefixname.go
  pkg/kinflate/transformers/prefixname_test.go
  pkg/kinflate/transformers/transformer.go
  pkg/kinflate/transformers/util_test.go
  pkg/kinflate/types/types.go
  pkg/kinflate/types/util.go
  pkg/kinflate/util/util.go
  pkg/kinflate/util/util_test.go
Labels: cncf-cla: yes, size/XXL

#352 fix bug when update name ref in multi layer setup
  pkg/kinflate/app/application.go
  pkg/kinflate/commands/testdata/testcase-single-overlay/expected.diff
  pkg/kinflate/commands/testdata/testcase-single-overlay/expected.yaml
Labels: cncf-cla: yes, size/M

#351 Add testing script to invoke example testing
  cmd/kinflate/test/main.sh
Labels: cncf-cla: yes, size/M

#355 Update main.sh to exit non-zero when there is a failure
  cmd/kinflate/test/main.sh
Labels: cncf-cla: yes, size/S

#354 unstructpath: Create json path type package.
  pkg/framework/unstructpath/doc.go
  pkg/framework/unstructpath/example_test.go
  pkg/framework/unstructpath/mapf.go
  pkg/framework/unstructpath/mapp.go
  pkg/framework/unstructpath/mapp_test.go
  pkg/framework/unstructpath/maps.go
  pkg/framework/unstructpath/numberp.go
  pkg/framework/unstructpath/numberp_test.go
  pkg/framework/unstructpath/numbers.go
  pkg/framework/unstructpath/numbers_test.go
  pkg/framework/unstructpath/slicef.go
  pkg/framework/unstructpath/slicep.go
  pkg/framework/unstructpath/slicep_test.go
  pkg/framework/unstructpath/slices.go
  pkg/framework/unstructpath/stringp.go
  pkg/framework/unstructpath/stringp_test.go
  pkg/framework/unstructpath/strings.go
  pkg/framework/unstructpath/strings_test.go
  pkg/framework/unstructpath/valuef.go
  pkg/framework/unstructpath/valuep.go
  pkg/framework/unstructpath/valuep_test.go
  pkg/framework/unstructpath/values.go
  pkg/framework/unstructpath/values_test.go
Labels: cncf-cla: yes, size/XXL

#356 Update directories in test script
  cmd/kinflate/test/main.sh
Labels: cncf-cla: yes, size/S

#359 unstructpath: Move predicates to their own package
  pkg/framework/predicates/map.go
  pkg/framework/predicates/map_test.go
  pkg/framework/predicates/number.go
  pkg/framework/predicates/number_test.go
  pkg/framework/predicates/slice.go
  pkg/framework/predicates/slice_test.go
  pkg/framework/predicates/string.go
  pkg/framework/predicates/string_test.go
  pkg/framework/predicates/value.go
  pkg/framework/predicates/value_test.go
  pkg/framework/unstructpath/example_test.go
  pkg/framework/unstructpath/mapf.go
  pkg/framework/unstructpath/maps.go
  pkg/framework/unstructpath/numbers.go
  pkg/framework/unstructpath/numbers_test.go
  pkg/framework/unstructpath/slicef.go
  pkg/framework/unstructpath/slices.go
  pkg/framework/unstructpath/strings.go
  pkg/framework/unstructpath/strings_test.go
  pkg/framework/unstructpath/valuef.go
  pkg/framework/unstructpath/values.go
Labels: cncf-cla: yes, size/L

#360 predicates: Rename Value into Interface
  pkg/framework/predicates/interface.go
  pkg/framework/predicates/interface_test.go
  pkg/framework/predicates/value.go
  pkg/framework/predicates/value_test.go
  pkg/framework/unstructpath/interfacef.go
  pkg/framework/unstructpath/interfaces.go
  pkg/framework/unstructpath/interfaces_test.go
  pkg/framework/unstructpath/mapf.go
  pkg/framework/unstructpath/maps.go
  pkg/framework/unstructpath/numbers.go
  pkg/framework/unstructpath/numbers_test.go
  pkg/framework/unstructpath/slicef.go
  pkg/framework/unstructpath/slices.go
  pkg/framework/unstructpath/strings.go
  pkg/framework/unstructpath/strings_test.go
Labels: cncf-cla: yes, size/XL

#362 selectors: Remove "Map" and "Slice"
  pkg/framework/path/predicates/interface.go
  pkg/framework/path/predicates/interface_test.go
  pkg/framework/path/predicates/map.go
  pkg/framework/path/predicates/map_test.go
  pkg/framework/path/predicates/number.go
  pkg/framework/path/predicates/number_test.go
  pkg/framework/path/predicates/slice.go
  pkg/framework/path/predicates/slice_test.go
  pkg/framework/path/predicates/string.go
  pkg/framework/path/predicates/string_test.go
  pkg/framework/path/selectors/doc.go
  pkg/framework/path/selectors/example_test.go
  pkg/framework/path/selectors/interface.go
  pkg/framework/path/selectors/interface_test.go
  pkg/framework/path/selectors/interfacef.go
  pkg/framework/path/selectors/map.go
  pkg/framework/path/selectors/number.go
  pkg/framework/path/selectors/number_test.go
  pkg/framework/path/selectors/slice.go
  pkg/framework/path/selectors/string.go
  pkg/framework/path/selectors/string_test.go
  pkg/framework/unstructpath/interfacef.go
  pkg/framework/unstructpath/interfaces.go
  pkg/framework/unstructpath/mapf.go
  pkg/framework/unstructpath/slicef.go
Labels: cncf-cla: yes, size/XL

#348 Use passed-in context in pluginutils config initializer
  pkg/pluginutils/plugin_client.go
  pkg/pluginutils/plugin_client_test.go
  pkg/pluginutils/testdata/config
Labels: cncf-cla: yes, size/S

#370 support multiple patches for the same GVKN
  pkg/kinflate/app/application.go
  pkg/kinflate/resource/appresource.go
  pkg/kinflate/resource/appresource_test.go
  pkg/kinflate/resource/util.go
  pkg/kinflate/transformers/overlay.go
  pkg/kinflate/transformers/overlay_test.go
Labels: cncf-cla: yes, size/M

#367 change packages to bases in Manifest
  cmd/kinflate/longerDemo/instances/production.md
  cmd/kinflate/longerDemo/instances/staging.md
  pkg/apis/manifest/v1alpha1/types.go
  pkg/kinflate/app/application.go
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/overlay/Kube-manifest.yaml
  pkg/kinflate/examples/simple/instances/exampleinstance/Kube-manifest.yaml
Labels: cncf-cla: yes, size/S

#379 A new hello-world demo.
  .travis.yml
  cmd/kinflate/longerDemo/README.md
  cmd/kinflate/longerDemo/README_ORDER.txt
  cmd/kinflate/longerDemo/base.md
  cmd/kinflate/longerDemo/clone.md
  cmd/kinflate/longerDemo/customization.md
  cmd/kinflate/longerDemo/customize.md
  cmd/kinflate/longerDemo/editor.md
  cmd/kinflate/longerDemo/identity.md
  cmd/kinflate/longerDemo/instances/README.md
  cmd/kinflate/longerDemo/instances/compare.md
  cmd/kinflate/longerDemo/instances/production.md
  cmd/kinflate/longerDemo/instances/staging.md
  cmd/kinflate/longerDemo/lifecycle.md
  cmd/kinflate/longerDemo/manifest.md
  cmd/kinflate/longerDemo/overlays/README.md
  cmd/kinflate/longerDemo/overlays/README_ORDER.txt
  cmd/kinflate/longerDemo/overlays/compare.md
  cmd/kinflate/longerDemo/overlays/deploy.md
  cmd/kinflate/longerDemo/overlays/production/manifest.md
  cmd/kinflate/longerDemo/overlays/production/patch.md
  cmd/kinflate/longerDemo/overlays/staging/manifest.md
  cmd/kinflate/longerDemo/overlays/staging/patch.md
  cmd/kinflate/longerDemo/resources.md
Labels: cncf-cla: yes, size/XL

#380 newshortdemo
  cmd/kinflate/README.md
  cmd/kinflate/getting_started.md
  cmd/kinflate/longerDemo/README.md
  cmd/kinflate/longerDemo/clone.md
  cmd/kinflate/longerDemo/manifest.md
  cmd/kinflate/longerDemo/overlays/README.md
  cmd/kinflate/longerDemo/overlays/compare.md
  cmd/kinflate/longerDemo/overlays/deploy.md
  cmd/kinflate/longerDemo/overlays/production/manifest.md
  cmd/kinflate/longerDemo/overlays/production/patch.md
  cmd/kinflate/longerDemo/overlays/staging/manifest.md
  cmd/kinflate/longerDemo/overlays/staging/patch.md
  cmd/kinflate/shortDemo.md
Labels: cncf-cla: yes, size/L

#381 renameDemos
  cmd/kinflate/README.md
  cmd/kinflate/demoHelloWorldLong/README.md
  cmd/kinflate/demoHelloWorldLong/README_ORDER.txt
  cmd/kinflate/demoHelloWorldLong/clone.md
  cmd/kinflate/demoHelloWorldLong/customize.md
  cmd/kinflate/demoHelloWorldLong/editor.md
  cmd/kinflate/demoHelloWorldLong/manifest.md
  cmd/kinflate/demoHelloWorldLong/overlays/README.md
  cmd/kinflate/demoHelloWorldLong/overlays/README_ORDER.txt
  cmd/kinflate/demoHelloWorldLong/overlays/compare.md
  cmd/kinflate/demoHelloWorldLong/overlays/deploy.md
  cmd/kinflate/demoHelloWorldLong/overlays/production/manifest.md
  cmd/kinflate/demoHelloWorldLong/overlays/production/patch.md
  cmd/kinflate/demoHelloWorldLong/overlays/staging/manifest.md
  cmd/kinflate/demoHelloWorldLong/overlays/staging/patch.md
  cmd/kinflate/demoHelloWorldShort.md
  cmd/kinflate/demoMySql.md
Labels: cncf-cla: yes, size/M

#377 detect unknown fields in Kube-manifest.yaml
  .travis.yml
  cmd/kinflate/README.md
  cmd/kinflate/demoHelloWorldLong/overlays/production/manifest.md
  cmd/kinflate/demoHelloWorldLong/overlays/staging/manifest.md
  cmd/kinflate/demoMySql.md
  pkg/kinflate/app/application.go
  pkg/kinflate/app/application_test.go
  pkg/kinflate/commands/testdata/testcase-base-only/in/Kube-manifest.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/overlay/Kube-manifest.yaml
  pkg/kinflate/commands/testdata/testcase-single-overlay/in/package/Kube-manifest.yaml
  pkg/kinflate/examples/simple/instances/exampleinstance/Kube-manifest.yaml
  pkg/kinflate/examples/simple/package/Kube-manifest.yaml
Labels: cncf-cla: yes, size/M

#382 combine demos into a subdir
  cmd/kinflate/README.md
  cmd/kinflate/demo/helloWorldDetailed/README.md
  cmd/kinflate/demo/helloWorldDetailed/README_ORDER.txt
  cmd/kinflate/demo/helloWorldDetailed/clone.md
  cmd/kinflate/demo/helloWorldDetailed/customize.md
  cmd/kinflate/demo/helloWorldDetailed/editor.md
  cmd/kinflate/demo/helloWorldDetailed/manifest.md
  cmd/kinflate/demo/helloWorldDetailed/overlays/README.md
  cmd/kinflate/demo/helloWorldDetailed/overlays/README_ORDER.txt
  cmd/kinflate/demo/helloWorldDetailed/overlays/compare.md
  cmd/kinflate/demo/helloWorldDetailed/overlays/deploy.md
  cmd/kinflate/demo/helloWorldDetailed/overlays/production/manifest.md
  cmd/kinflate/demo/helloWorldDetailed/overlays/production/patch.md
  cmd/kinflate/demo/helloWorldDetailed/overlays/staging/manifest.md
  cmd/kinflate/demo/helloWorldDetailed/overlays/staging/patch.md
  cmd/kinflate/demo/helloWorldOnePager.md
  cmd/kinflate/demo/mySql.md
Labels: cncf-cla: yes, size/S

#387 integrated glog in command structure
  cmd/kinflate/kinflate.go
  pkg/kinflate/commands/commands.go
Labels: cncf-cla: yes, size/S
