Repository kubernetes/kubectl, pull requests merged in 2019-04, with the labels that each got.

#636 fix typo
  docs/book/pages/resource_printing/raw.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#638 Book: update labeling recommendations
  docs/book/pages/app_management/labels_and_annotations.md
Labels: approved, cncf-cla: yes, size/S

#640 Update lodash to address CVE-2018-16487
  docs/book/package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#641 Update docs to clarify namespace overrides
  docs/book/pages/app_management/namespaces_and_names.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#626 Dockerfile for GitBook
  docs/book/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#643 Fix Invalid DNS ConfigMap Name
  docs/book/pages/app_customization/bases_and_variants.md
  docs/book/pages/app_management/secrets_and_configmaps.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#645 fix typo in JSON Path Symbols Table
  docs/book/pages/resource_printing/fields.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#634 feat(docs): add section on environment style configmap/secret generation
  docs/book/pages/app_management/secrets_and_configmaps.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#647 Add reference documentation for Kustomize in Kubectl
  docs/book/SUMMARY.md
  docs/book/book.json
  docs/book/pages/app_customization/bases_and_variants.md
  docs/book/pages/app_customization/config_reflection.md
  docs/book/pages/app_customization/customizing_arbitrary_fields.md
  docs/book/pages/app_customization/customizing_metadata.md
  docs/book/pages/app_customization/customizing_pod_templates.md
  docs/book/pages/app_management/container_images.md
  docs/book/pages/app_management/labels_and_annotations.md
  docs/book/pages/app_management/namespaces_and_names.md
  docs/book/pages/app_management/secrets_and_configmaps.md
  docs/book/pages/examples/kustomize.md
  docs/book/pages/reference/kustomize.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL
