Repository kubernetes/kubectl, pull requests merged in 2019-03, with the labels that each got.

#604 add gitbook-cli into kubectl book package.json
  docs/book/npm-shrinkwrap.json
  docs/book/package.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#607 add google analytics to kubectl book
  docs/book/book.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#608 Kubectl Book: Add Favicon and clean wording
  docs/book/book.json
  docs/book/favicon.ico
  docs/book/npm-shrinkwrap.json
  docs/book/package.json
  docs/book/pages/kubectl_book/kubectl.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#609 GitBook: Refine App Composition and Deployment guidelines
  docs/book/SUMMARY.md
  docs/book/pages/app_composition_and_deployment/publishing_bases.md
  docs/book/pages/app_composition_and_deployment/structure_branches.md
  docs/book/pages/app_composition_and_deployment/structure_directories.md
  docs/book/pages/app_composition_and_deployment/structure_multi_tier_apps.md
  docs/book/pages/app_composition_and_deployment/structure_repositories.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#610 Refine App Composition and Deployment guidelines
  docs/book/SUMMARY.md
  docs/book/pages/app_composition_and_deployment/structure_directories.md
  docs/book/pages/app_composition_and_deployment/structure_multi_tier_apps.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#611 Various fixes
  docs/book/README.md
  docs/book/pages/app_composition_and_deployment/accessing_multiple_clusters.md
  docs/book/pages/app_composition_and_deployment/diffing_local_and_remote_resources.md
  docs/book/pages/app_composition_and_deployment/publishing_bases.md
  docs/book/pages/app_composition_and_deployment/structure_branches.md
  docs/book/pages/app_composition_and_deployment/structure_multi_tier_apps.md
  docs/book/pages/app_customization/config_reflection.md
  docs/book/pages/app_customization/customizing_arbitrary_fields.md
  docs/book/pages/app_customization/customizing_pod_templates.md
  docs/book/pages/app_management/container_images.md
  docs/book/pages/app_management/labels_and_annotations.md
  docs/book/pages/app_management/secrets_and_configmaps.md
  docs/book/pages/container_debugging/copying_container_files.md
  docs/book/pages/container_debugging/executing_a_command_in_a_container.md
  docs/book/pages/container_debugging/proxying_traffic_to_services.md
  docs/book/pages/imperative_porcelain/creating_resources.md
  docs/book/pages/imperative_porcelain/setting_fields.md
  docs/book/pages/resource_printing/fields.md
  docs/book/pages/resource_printing/raw.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#612 kubectl book - add `newName` function
  docs/book/pages/app_composition_and_deployment/accessing_multiple_clusters.md
  docs/book/pages/app_composition_and_deployment/diffing_local_and_remote_resources.md
  docs/book/pages/app_composition_and_deployment/structure_branches.md
  docs/book/pages/app_composition_and_deployment/structure_directories.md
  docs/book/pages/app_composition_and_deployment/structure_repositories.md
  docs/book/pages/app_customization/customizing_pod_templates.md
  docs/book/pages/app_management/apply.md
  docs/book/pages/app_management/container_images.md
  docs/book/pages/container_debugging/container_logs.md
  docs/book/pages/container_debugging/copying_container_files.md
  docs/book/pages/container_debugging/executing_a_command_in_a_container.md
  docs/book/pages/container_debugging/port_forward_to_pods.md
  docs/book/pages/container_debugging/proxying_traffic_to_services.md
  docs/book/pages/resource_printing/cluster_information.md
  docs/book/pages/resource_printing/describe.md
  docs/book/pages/resource_printing/fields.md
  docs/book/pages/resource_printing/queries_and_options.md
  docs/book/pages/resource_printing/raw.md
  docs/book/pages/resource_printing/summaries.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#616 GitBook: Update structure titles
  docs/book/SUMMARY.md
  docs/book/pages/app_composition_and_deployment/structure_branches.md
  docs/book/pages/app_composition_and_deployment/structure_directories.md
  docs/book/pages/app_composition_and_deployment/structure_repositories.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#617 kubectl book: Fix exec examples caused by bad refactoring
  docs/book/pages/app_composition_and_deployment/accessing_multiple_clusters.md
  docs/book/pages/app_composition_and_deployment/diffing_local_and_remote_resources.md
  docs/book/pages/app_composition_and_deployment/structure_branches.md
  docs/book/pages/app_composition_and_deployment/structure_directories.md
  docs/book/pages/app_composition_and_deployment/structure_repositories.md
  docs/book/pages/app_management/apply.md
  docs/book/pages/app_management/container_images.md
  docs/book/pages/container_debugging/container_logs.md
  docs/book/pages/container_debugging/copying_container_files.md
  docs/book/pages/container_debugging/executing_a_command_in_a_container.md
  docs/book/pages/container_debugging/port_forward_to_pods.md
  docs/book/pages/container_debugging/proxying_traffic_to_services.md
  docs/book/pages/resource_printing/cluster_information.md
  docs/book/pages/resource_printing/describe.md
  docs/book/pages/resource_printing/fields.md
  docs/book/pages/resource_printing/queries_and_options.md
  docs/book/pages/resource_printing/raw.md
  docs/book/pages/resource_printing/summaries.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#602 Update embargo doc link in SECURITY_CONTACTS and change PST to PSC
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#619 Adds kubectl logo to repository
  README.md
  images/kubectl-logo-full.png
  images/kubectl-logo-medium.png
  images/kubectl-logo-small.png
Labels: approved, cncf-cla: yes, lgtm, size/XS

#618 Address Doc Feedback
  docs/book/README.md
  docs/book/SUMMARY.md
  docs/book/book.json
  docs/book/examples/nginx/deployment.yaml
  docs/book/examples/nginx/kustomization.yaml
  docs/book/examples/nginx/service.yaml
  docs/book/npm-shrinkwrap.json
  docs/book/package.json
  docs/book/pages/app_composition_and_deployment/publishing_bases.md
  docs/book/pages/app_composition_and_deployment/structure_branches.md
  docs/book/pages/app_composition_and_deployment/structure_directories.md
  docs/book/pages/app_composition_and_deployment/structure_introduction.md
  docs/book/pages/app_composition_and_deployment/structure_multi_tier_apps.md
  docs/book/pages/app_composition_and_deployment/structure_repositories.md
  docs/book/pages/app_customization/bases_and_variants.md
  docs/book/pages/app_customization/customizing_pod_templates.md
  docs/book/pages/app_customization/introduction.md
  docs/book/pages/app_management/apply.md
  docs/book/pages/app_management/container_images.md
  docs/book/pages/app_management/field_merge_semantics.md
  docs/book/pages/app_management/introduction.md
  docs/book/pages/app_management/namespaces_and_names.md
  docs/book/pages/kubectl_book/getting_started.md
  docs/book/pages/kubectl_book/kubectl.md
  docs/book/pages/kubectl_book/resources_and_controllers.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#620 Kubectl Book Final Edits
  docs/book/CONTRIBUTING.md
  docs/book/README.md
  docs/book/SUMMARY.md
  docs/book/pages/app_composition_and_deployment/publishing_bases.md
  docs/book/pages/app_composition_and_deployment/structure_branches.md
  docs/book/pages/app_composition_and_deployment/structure_directories.md
  docs/book/pages/app_composition_and_deployment/structure_multi_tier_apps.md
  docs/book/pages/app_composition_and_deployment/structure_repositories.md
  docs/book/pages/app_customization/bases_and_variants.md
  docs/book/pages/kubectl_book/getting_started.md
Labels: approved, cncf-cla: yes, size/L

#621 Fix examples
  docs/book/examples/nginx/kustomization.yaml
  docs/book/examples/nginx/nginx.yaml
  docs/book/examples/nginx/service.yaml
Labels: cncf-cla: yes

#630 fix(docs): Fix typo and command reference
  docs/book/pages/app_management/field_merge_semantics.md
  docs/book/pages/resource_printing/cluster_information.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#633 Fixed a typo in field merge semantics
  docs/book/pages/app_management/field_merge_semantics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#635 replaced Conainer with Container
  docs/book/pages/container_debugging/copying_container_files.md
  docs/book/pages/container_debugging/port_forward_to_pods.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#624 Remove cp examples from the port-forward page
  docs/book/pages/container_debugging/port_forward_to_pods.md
Labels: approved, cncf-cla: yes, lgtm, size/M
